public class Serialize_Deserialize 
{
	/*
	 * 
	 * String JCUst = '{"Name":"Omar", "Phone":"777", "Fax":"888","Active__c":"Yes","AnnualRevenue":"99999"}';
    Account Acc = (Account) JSON.deserialize(JCust, Account.class);
    // Insert Acc;
    //System.debug(Acc);
    //System.debug(JCust);
    Map<String, Object> ACC3 = (Map<String,Object>) JSON.deserializeUntyped(JCUst);
    System.debug(ACC3);
    System.debug(ACC3.keyset());
    System.debug(ACC3.values());


	Account[] acc = [select id, name from Account limit 4];
    system.debug(acc);
    
    String JS = (String) JSON.serialize(acc);
    System.debug(JS);
    String JS1 = (String) JSON.serializePretty(acc);
    System.debug(JS1);
    */
}